# Generated by Django 3.2.5 on 2021-11-21 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='profie_pic',
            new_name='profile_pic',
        ),
    ]
